// <auto-generated>
//   This code was generated by openapi2zig 0.5.6 (42c672b) on 2026-09-10 01:16:41 UTC
//   Changes to this file may cause incorrect behavior and will be lost if the code is regenerated
//   Checksum: 5f80a4d232c691db
// </auto-generated>

const std = @import("std");

pub const DigestJsonLeaguesItemGamesItemParticipantsItem = struct {
    record: ?[]const u8,
    abbreviation: []const u8,
    winner: bool,
    score: []const u8,
    home_away: ?[]const u8,
    id: []const u8,
    name: []const u8,
};

pub const DigestJsonLeaguesItemGamesItem = struct {
    status: []const u8,
    starts_at: []const u8,
    participants: []const DigestJsonLeaguesItemGamesItemParticipantsItem,
    id: []const u8,
    name: []const u8,
    state: []const u8,
};

pub const DigestJsonLeaguesItem = struct {
    source: []const u8,
    date: []const u8,
    games: []const DigestJsonLeaguesItemGamesItem,
    schema_version: []const u8,
    league: []const u8,
    league_name: []const u8,
};

pub const DigestJson = struct {
    date: []const u8,
    schema_version: []const u8,
    degraded: []const []const u8,
    leagues: []const DigestJsonLeaguesItem,
};

pub const ErrorBodyErrorsItem = struct {
    pointer: []const u8,
    message: []const u8,
};

pub const ErrorBody = struct {
    status: i64,
    detail: ?[]const u8 = null,
    errors: []const ErrorBodyErrorsItem,
    type: []const u8,
    instance: ?[]const u8 = null,
    title: []const u8,
};

pub const DetailGameLineupsItemEntriesItem = struct {
    runs: []const u8,
    hitting: []const u8,
    position: []const u8,
    walks: []const u8,
    rbis: []const u8,
    order: i64,
    name: []const u8,
    average: []const u8,
    strikeouts: []const u8,
};

pub const DetailGameLineupsItem = struct {
    entries: []const DetailGameLineupsItemEntriesItem,
    team: []const u8,
    total: []const u8,
};

pub const DetailGameParticipantsItemLinesItem = struct {
    period: ?i64,
    display: []const u8,
};

pub const DetailGameParticipantsItem = struct {
    hits: ?[]const u8,
    errors: ?[]const u8,
    abbreviation: []const u8,
    record: ?[]const u8,
    winner: bool,
    score: []const u8,
    home_away: ?[]const u8,
    probable: ?[]const u8,
    id: []const u8,
    name: []const u8,
    lines: []const DetailGameParticipantsItemLinesItem,
};

pub const DetailGameSituation = ?std.json.Value;

pub const DetailGameDecisionsItem = struct {
    outcome: []const u8,
    name: []const u8,
};

pub const DetailGameScoringPlaysItem = struct {
    text: []const u8,
    period: []const u8,
    home_score: []const u8,
    away_score: []const u8,
};

pub const DetailGame = struct {
    lineups: []const DetailGameLineupsItem,
    state: []const u8,
    league: []const u8,
    league_name: []const u8,
    series: ?[]const u8,
    status: []const u8,
    venue: ?[]const u8,
    participants: []const DetailGameParticipantsItem,
    situation: ?DetailGameSituation,
    id: []const u8,
    team_stats: []const []const u8,
    attendance: ?i64,
    decisions: []const DetailGameDecisionsItem,
    date: []const u8,
    schema_version: []const u8,
    scoring_plays: []const DetailGameScoringPlaysItem,
    leaders: []const []const u8,
};

pub const ScoreboardGamesItemParticipantsItem = struct {
    record: ?[]const u8,
    abbreviation: []const u8,
    winner: bool,
    score: []const u8,
    home_away: ?[]const u8,
    id: []const u8,
    name: []const u8,
};

pub const ScoreboardGamesItem = struct {
    status: []const u8,
    starts_at: []const u8,
    participants: []const ScoreboardGamesItemParticipantsItem,
    id: []const u8,
    name: []const u8,
    state: []const u8,
};

pub const Scoreboard = struct {
    source: []const u8,
    date: []const u8,
    games: []const ScoreboardGamesItem,
    schema_version: []const u8,
    league: []const u8,
    league_name: []const u8,
};

pub const LeagueStandingsGroupsItemEntriesItem = struct {
    wins: ?[]const u8,
    team_id: []const u8,
    ties: ?[]const u8,
    losses: ?[]const u8,
    points: ?[]const u8,
    abbrev: []const u8,
    name: []const u8,
};

pub const LeagueStandingsGroupsItem = struct {
    entries: []const LeagueStandingsGroupsItemEntriesItem,
    name: []const u8,
};

pub const LeagueStandings = struct {
    groups: []const LeagueStandingsGroupsItem,
    season: []const u8,
    source: []const u8,
    schema_version: []const u8,
    league: []const u8,
    league_name: []const u8,
};

pub const ScheduleTeamViewTeam = struct {
    abbrev: []const u8,
    id: []const u8,
    name: []const u8,
    record_summary: ?[]const u8,
    standing_summary: ?[]const u8,
};

pub const ScheduleTeamViewNextItem = struct {
    opponent_name: []const u8,
    result: []const u8,
    state: []const u8,
    today: bool,
    our_score: []const u8,
    status: []const u8,
    date: []const u8,
    opponent_abbrev: []const u8,
    home_away: []const u8,
    id: []const u8,
    opp_score: []const u8,
    probable: []const u8,
};

pub const ScheduleTeamViewLive = ?std.json.Value;

pub const ScheduleTeamViewExtraPastItem = struct {
    opponent_name: []const u8,
    result: []const u8,
    state: []const u8,
    today: bool,
    our_score: []const u8,
    status: []const u8,
    date: []const u8,
    opponent_abbrev: []const u8,
    home_away: []const u8,
    id: []const u8,
    opp_score: []const u8,
    probable: []const u8,
};

pub const ScheduleTeamViewLastItem = struct {
    opponent_name: []const u8,
    result: []const u8,
    state: []const u8,
    today: bool,
    our_score: []const u8,
    status: []const u8,
    date: []const u8,
    opponent_abbrev: []const u8,
    home_away: []const u8,
    id: []const u8,
    opp_score: []const u8,
    probable: []const u8,
};

pub const ScheduleTeamViewExtraNextItem = struct {
    opponent_name: []const u8,
    result: []const u8,
    state: []const u8,
    today: bool,
    our_score: []const u8,
    status: []const u8,
    date: []const u8,
    opponent_abbrev: []const u8,
    home_away: []const u8,
    id: []const u8,
    opp_score: []const u8,
    probable: []const u8,
};

pub const ScheduleTeamView = struct {
    team: ScheduleTeamViewTeam,
    league: []const u8,
    next: []const ScheduleTeamViewNextItem,
    league_name: []const u8,
    schema_version: []const u8,
    live: ?ScheduleTeamViewLive,
    extra_past: []const ScheduleTeamViewExtraPastItem,
    last: []const ScheduleTeamViewLastItem,
    extra_next: []const ScheduleTeamViewExtraNextItem,
};

pub const LeagueListLeaguesItem = struct {
    name: []const u8,
    sport: []const u8,
    slug: []const u8,
};

pub const LeagueList = struct {
    schema_version: []const u8,
    leagues: []const LeagueListLeaguesItem,
};

pub fn Owned(comptime T: type) type {
    return struct {
        allocator: std.mem.Allocator,
        body: []u8,
        parsed: std.json.Parsed(T),

        pub fn deinit(self: *@This()) void {
            self.parsed.deinit();
            self.allocator.free(self.body);
        }

        pub fn value(self: *@This()) *T {
            return &self.parsed.value;
        }
    };
}

pub const RawResponse = struct {
    allocator: std.mem.Allocator,
    status: std.http.Status,
    body: []u8,

    pub fn deinit(self: *@This()) void {
        self.allocator.free(self.body);
    }
};

pub const ParseErrorResponse = struct {
    raw: RawResponse,
    error_name: []const u8,
};

pub fn ApiResult(comptime T: type) type {
    return union(enum) {
        ok: Owned(T),
        api_error: RawResponse,
        parse_error: ParseErrorResponse,

        pub fn deinit(self: *@This()) void {
            switch (self.*) {
                .ok => |*value| value.deinit(),
                .api_error => |*value| value.deinit(),
                .parse_error => |*value| value.raw.deinit(),
            }
        }
    };
}

pub const HttpObserver = struct {
    ctx: ?*anyopaque,
    onRequest: ?*const fn (ctx: ?*anyopaque, method: std.http.Method, url: []const u8, headers: []const std.http.Header, body: ?[]const u8) void,
    onResponse: ?*const fn (ctx: ?*anyopaque, method: std.http.Method, url: []const u8, status: std.http.Status, headers: []const std.http.Header, body: []const u8, duration_ns: u64) void,
    onError: ?*const fn (ctx: ?*anyopaque, method: std.http.Method, url: []const u8, err_name: []const u8) void,
};

pub const Client = struct {
    allocator: std.mem.Allocator,
    io: std.Io,
    http: std.http.Client,
    api_key: []const u8,
    base_url: []const u8 = "http://localhost:8080/api/v1",
    organization: ?[]const u8 = null,
    project: ?[]const u8 = null,
    default_headers: []const std.http.Header = &.{},
    http_observer: ?HttpObserver = null,

    /// Optional predicate polled while reading a streaming response body.
    /// When it returns true, a successfully started background watcher interrupts
    /// a blocked SSE socket read within about 10 ms and the stream exits with
    /// error.Cancelled. A CancelableReader also checks the predicate at every read
    /// boundary. If watcher startup fails, cancellation remains read-boundary only.
    /// Point it at an app-level cancel flag; it composes with a CancellationToken.
    /// When null (default), no watcher thread is spawned.
    cancel_check: ?*const fn () bool = null,

    pub fn init(allocator: std.mem.Allocator, io: std.Io, api_key: []const u8) Client {
        return .{
            .allocator = allocator,
            .io = io,
            .http = .{ .allocator = allocator, .io = io },
            .api_key = api_key,
            .http_observer = null,
        };
    }

    pub fn deinit(self: *Client) void {
        self.http.deinit();
    }

    pub fn withBaseUrl(self: *Client, base_url: []const u8) void {
        self.base_url = base_url;
    }
};

fn isQueryChar(c: u8) bool {
    return std.ascii.isAlphanumeric(c) or switch (c) {
        '-', '.', '_', '~' => true,
        else => false,
    };
}

fn writeQueryComponent(writer: *std.Io.Writer, value: []const u8) !void {
    try std.Uri.Component.percentEncode(writer, value, isQueryChar);
}

fn writeQueryValue(writer: *std.Io.Writer, value: anytype) !void {
    const T = @TypeOf(value);
    switch (@typeInfo(T)) {
        .pointer => |ptr| {
            if (ptr.size == .slice and ptr.child == u8) {
                try writeQueryComponent(writer, value);
            } else {
                try std.json.Stringify.value(value, .{}, writer);
            }
        },
        .int, .comptime_int, .float, .comptime_float, .bool => try writer.print("{}", .{value}),
        .@"enum" => try writeQueryComponent(writer, @tagName(value)),
        else => try std.json.Stringify.value(value, .{}, writer),
    }
}

fn appendQueryParam(writer: *std.Io.Writer, first_query: *bool, name: []const u8, value: anytype) !void {
    if (first_query.*) {
        try writer.writeByte('?');
        first_query.* = false;
    } else {
        try writer.writeByte('&');
    }
    try writeQueryComponent(writer, name);
    try writer.writeByte('=');
    try writeQueryValue(writer, value);
}

/// Serializes an `in: header` parameter value to an owned string. Reuses
/// the same primitive-type coverage as query parameters (string, integer,
/// float, boolean, enum). The caller frees the returned slice.
fn formatHeaderValue(allocator: std.mem.Allocator, value: anytype) ![]u8 {
    const T = @TypeOf(value);
    return switch (@typeInfo(T)) {
        .pointer => |ptr| blk: {
            if (ptr.size == .slice and ptr.child == u8) {
                break :blk try allocator.dupe(u8, value);
            }
            @compileError("OpenAPI header values must be strings, numbers, booleans, or enums");
        },
        .@"enum" => try allocator.dupe(u8, @tagName(value)),
        .int, .comptime_int, .float, .comptime_float, .bool => try std.fmt.allocPrint(allocator, "{}", .{value}),
        else => @compileError("OpenAPI header values must be strings, numbers, booleans, or enums"),
    };
}

/// Appends `value` under `name`, replacing (case-insensitively) any
/// existing header of the same name. Used so a declared operation header
/// parameter always wins over an equal-named client default header while
/// emitting exactly one header on the wire.
fn appendOrReplaceHeader(allocator: std.mem.Allocator, headers: *std.ArrayList(std.http.Header), name: []const u8, value: []const u8) !void {
    var i: usize = 0;
    while (i < headers.items.len) {
        if (std.ascii.eqlIgnoreCase(headers.items[i].name, name)) {
            _ = headers.orderedRemove(i);
        } else {
            i += 1;
        }
    }
    try headers.append(allocator, .{ .name = name, .value = value });
}

pub fn requestRaw(client: *Client, method: std.http.Method, url: []const u8, payload: ?[]const u8) !RawResponse {
    return requestRawWithContentType(client, method, url, payload, "application/json");
}

pub fn requestRawWithExtraHeaders(client: *Client, method: std.http.Method, url: []const u8, payload: ?[]const u8, extra_headers: []const std.http.Header) !RawResponse {
    return requestRawWithContentTypeAndExtraHeaders(client, method, url, payload, "application/json", extra_headers);
}

pub fn requestRawWithContentTypeAndExtraHeaders(client: *Client, method: std.http.Method, url: []const u8, payload: ?[]const u8, content_type_value: []const u8, extra_headers: []const std.http.Header) !RawResponse {
    const allocator = client.allocator;
    var headers = std.ArrayList(std.http.Header).empty;
    defer headers.deinit(allocator);
    const content_type: ?[]const u8 = if (payload != null) content_type_value else null;
    try appendClientHeaders(allocator, &headers, client, content_type, "application/json");
    for (extra_headers) |header| try appendOrReplaceHeader(allocator, &headers, header.name, header.value);

    if (client.http_observer) |obs| {
        if (obs.onRequest) |cb| cb(obs.ctx, method, url, headers.items, payload);
    }

    const uri = try std.Uri.parse(url);
    var response_body: std.Io.Writer.Allocating = .init(allocator);
    defer response_body.deinit();

    const start = std.Io.Clock.awake.now(client.io);
    const result = client.http.fetch(.{
        .location = .{ .uri = uri },
        .method = method,
        .extra_headers = headers.items,
        .payload = payload,
        .response_writer = &response_body.writer,
    }) catch |err| {
        if (client.http_observer) |obs| {
            if (obs.onError) |cb| cb(obs.ctx, method, url, @errorName(err));
        }
        return err;
    };
    const elapsed_ns = @as(u64, @intCast(start.untilNow(client.io, .awake).nanoseconds));

    const body = try response_body.toOwnedSlice();

    if (client.http_observer) |obs| {
        if (obs.onResponse) |cb| cb(obs.ctx, method, url, result.status, &.{}, body, elapsed_ns);
    }

    return .{
        .allocator = allocator,
        .status = result.status,
        .body = body,
    };
}

pub fn requestRawWithContentType(client: *Client, method: std.http.Method, url: []const u8, payload: ?[]const u8, content_type_value: []const u8) !RawResponse {
    const allocator = client.allocator;
    var headers = std.ArrayList(std.http.Header).empty;
    defer headers.deinit(allocator);
    const content_type: ?[]const u8 = if (payload != null) content_type_value else null;
    try appendClientHeaders(allocator, &headers, client, content_type, "application/json");

    if (client.http_observer) |obs| {
        if (obs.onRequest) |cb| cb(obs.ctx, method, url, headers.items, payload);
    }

    const uri = try std.Uri.parse(url);
    var response_body: std.Io.Writer.Allocating = .init(allocator);
    defer response_body.deinit();

    const start = std.Io.Clock.awake.now(client.io);
    const result = client.http.fetch(.{
        .location = .{ .uri = uri },
        .method = method,
        .extra_headers = headers.items,
        .payload = payload,
        .response_writer = &response_body.writer,
    }) catch |err| {
        if (client.http_observer) |obs| {
            if (obs.onError) |cb| cb(obs.ctx, method, url, @errorName(err));
        }
        return err;
    };
    const elapsed_ns = @as(u64, @intCast(start.untilNow(client.io, .awake).nanoseconds));

    const body = try response_body.toOwnedSlice();

    if (client.http_observer) |obs| {
        if (obs.onResponse) |cb| cb(obs.ctx, method, url, result.status, &.{}, body, elapsed_ns);
    }

    return .{
        .allocator = allocator,
        .status = result.status,
        .body = body,
    };
}

pub fn getRaw(client: *Client, path: []const u8) !RawResponse {
    const url = try std.fmt.allocPrint(client.allocator, "{s}{s}", .{ client.base_url, path });
    defer client.allocator.free(url);
    return requestRaw(client, .GET, url, null);
}

pub fn postJsonRaw(client: *Client, path: []const u8, payload: anytype) !RawResponse {
    const allocator = client.allocator;
    var str: std.Io.Writer.Allocating = .init(allocator);
    defer str.deinit();
    try std.json.Stringify.value(payload, .{ .emit_null_optional_fields = false }, &str.writer);

    const url = try std.fmt.allocPrint(allocator, "{s}{s}", .{ client.base_url, path });
    defer allocator.free(url);
    return requestRaw(client, .POST, url, str.written());
}

pub fn parseRawResponse(comptime T: type, raw: RawResponse) !ApiResult(T) {
    if (raw.status.class() != .success) return .{ .api_error = raw };
    const parsed = std.json.parseFromSlice(T, raw.allocator, raw.body, .{ .ignore_unknown_fields = true }) catch |err| {
        return .{ .parse_error = .{ .raw = raw, .error_name = @errorName(err) } };
    };
    return .{ .ok = .{ .allocator = raw.allocator, .body = raw.body, .parsed = parsed } };
}

pub fn getJsonResult(comptime T: type, client: *Client, path: []const u8) !ApiResult(T) {
    return parseRawResponse(T, try getRaw(client, path));
}

pub fn postJsonResult(comptime T: type, client: *Client, path: []const u8, payload: anytype) !ApiResult(T) {
    return parseRawResponse(T, try postJsonRaw(client, path, payload));
}
fn appendClientHeaders(allocator: std.mem.Allocator, headers: *std.ArrayList(std.http.Header), client: *Client, content_type: ?[]const u8, accept: []const u8) !void {
    if (content_type) |ct| {
        try headers.append(allocator, .{ .name = "Content-Type", .value = ct });
    }
    try headers.append(allocator, .{ .name = "Accept", .value = accept });
    if (client.organization) |organization| {
        try headers.append(allocator, .{ .name = "OpenAI-Organization", .value = organization });
    }
    if (client.project) |project| {
        try headers.append(allocator, .{ .name = "OpenAI-Project", .value = project });
    }
    for (client.default_headers) |header| {
        try headers.append(allocator, header);
    }
}

pub const CancellationToken = struct {
    cancelled: std.atomic.Value(bool),

    pub fn init() CancellationToken {
        return .{ .cancelled = std.atomic.Value(bool).init(false) };
    }

    pub fn cancel(self: *CancellationToken) void {
        self.cancelled.store(true, .seq_cst);
    }

    pub fn isCancelled(self: *CancellationToken) bool {
        return self.cancelled.load(.seq_cst);
    }
};

fn checkCancellation(token: ?*CancellationToken) !void {
    if (token) |t| {
        if (t.isCancelled()) return error.Cancelled;
    }
}

/// Wraps an underlying reader and checks an optional cancel predicate before
/// every read of the underlying reader. When the predicate returns true, the
/// read fails with error.ReadFailed; callers translate that into
/// error.Cancelled. Cancellation is only observed at read boundaries: a read
/// already blocked inside the underlying reader (e.g. waiting for the next SSE
/// chunk on the socket) is not aborted until that read returns.
pub const CancelableReader = struct {
    inner: *std.Io.Reader,
    reader: std.Io.Reader,
    should_cancel: ?*const fn () bool,

    pub fn init(inner: *std.Io.Reader, buffer: []u8, should_cancel: ?*const fn () bool) CancelableReader {
        return .{
            .inner = inner,
            .reader = .{
                .buffer = buffer,
                .seek = 0,
                .end = 0,
                .vtable = &vtable,
            },
            .should_cancel = should_cancel,
        };
    }

    const vtable: std.Io.Reader.VTable = .{
        .stream = stream,
        .discard = std.Io.Reader.defaultDiscard,
        .readVec = std.Io.Reader.defaultReadVec,
        .rebase = std.Io.Reader.defaultRebase,
    };

    fn stream(ctx: *std.Io.Reader, w: *std.Io.Writer, limit: std.Io.Limit) std.Io.Reader.StreamError!usize {
        const self: *CancelableReader = @fieldParentPtr("reader", ctx);
        if (self.should_cancel) |pred| {
            if (pred()) return error.ReadFailed;
        }
        return self.inner.stream(w, limit);
    }
};

pub fn parseSseBytes(allocator: std.mem.Allocator, bytes: []const u8, callback: anytype, cancellation_token: ?*CancellationToken) !void {
    var reader: std.Io.Reader = .fixed(bytes);
    try parseSseReader(allocator, &reader, callback, cancellation_token);
}

pub fn parseSseReader(allocator: std.mem.Allocator, reader: *std.Io.Reader, callback: anytype, cancellation_token: ?*CancellationToken) !void {
    var line_buf: std.Io.Writer.Allocating = .init(allocator);
    defer line_buf.deinit();

    var event_data: std.Io.Writer.Allocating = .init(allocator);
    defer event_data.deinit();

    while (true) {
        try checkCancellation(cancellation_token);
        line_buf.clearRetainingCapacity();

        _ = reader.streamDelimiterLimit(&line_buf.writer, '\n', .limited(max_sse_line_size)) catch |err| switch (err) {
            error.StreamTooLong => return error.SseLineTooLong,
            error.ReadFailed => return err,
            error.WriteFailed => return err,
        };

        const ended_with_delimiter = blk: {
            const byte = reader.peekByte() catch |err| switch (err) {
                error.EndOfStream => break :blk false,
                error.ReadFailed => return err,
            };
            if (byte == '\n') {
                _ = try reader.takeByte();
                break :blk true;
            }
            break :blk false;
        };

        if (try processSseLine(&event_data, line_buf.written(), callback)) return;
        if (!ended_with_delimiter) break;
    }

    _ = try dispatchSseEvent(&event_data, callback);
}

fn processSseLine(event_data: *std.Io.Writer.Allocating, raw_line: []const u8, callback: anytype) !bool {
    const line = std.mem.trimEnd(u8, raw_line, "\r");
    if (line.len == 0) return try dispatchSseEvent(event_data, callback);
    if (line[0] == ':') return false;

    const colon = std.mem.indexOfScalar(u8, line, ':') orelse return false;
    const field = line[0..colon];
    if (!std.mem.eql(u8, field, "data")) return false;

    var value = line[colon + 1 ..];
    if (value.len > 0 and value[0] == ' ') value = value[1..];
    const separator_len: usize = if (event_data.written().len == 0) 0 else 1;
    if (event_data.written().len + separator_len + value.len > max_sse_event_size) return error.SseEventTooLong;
    if (separator_len != 0) try event_data.writer.writeByte('\n');
    try event_data.writer.writeAll(value);
    return false;
}

fn dispatchSseEvent(event_data: *std.Io.Writer.Allocating, callback: anytype) !bool {
    const data = event_data.written();
    if (data.len == 0) return false;
    defer event_data.clearRetainingCapacity();

    if (std.mem.eql(u8, data, "[DONE]")) return true;
    try callback.event(data);
    return false;
}

fn TypedSseCallback(comptime T: type, comptime Callback: type) type {
    return struct {
        allocator: std.mem.Allocator,
        callback: *Callback,

        pub fn event(self: *@This(), data: []const u8) !void {
            var parsed = try std.json.parseFromSlice(T, self.allocator, data, .{ .ignore_unknown_fields = true });
            defer parsed.deinit();
            try self.callback.event(&parsed.value);
        }
    };
}

pub fn parseSseBytesTyped(comptime T: type, allocator: std.mem.Allocator, bytes: []const u8, callback: anytype, cancellation_token: ?*CancellationToken) !void {
    const Callback = @TypeOf(callback.*);
    var typed_callback: TypedSseCallback(T, Callback) = .{ .allocator = allocator, .callback = callback };
    try parseSseBytes(allocator, bytes, &typed_callback, cancellation_token);
}

pub fn parseSseReaderTyped(comptime T: type, allocator: std.mem.Allocator, reader: *std.Io.Reader, callback: anytype, cancellation_token: ?*CancellationToken) !void {
    const Callback = @TypeOf(callback.*);
    var typed_callback: TypedSseCallback(T, Callback) = .{ .allocator = allocator, .callback = callback };
    try parseSseReader(allocator, reader, &typed_callback, cancellation_token);
}
const max_sse_line_size = 256 * 1024;
const max_sse_event_size = 1024 * 1024;

/////////////////
// Summary:
// Current standings table for one league
//
pub fn getStandings(client: *Client, league: []const u8) !Owned(LeagueStandings) {
    var result = try getStandingsResult(client, league);
    switch (result) {
        .ok => |ok| return ok,
        .api_error => |*err| {
            err.deinit();
            return error.ResponseError;
        },
        .parse_error => |*err| {
            err.raw.deinit();
            return error.ResponseParseError;
        },
    }
}

pub fn getStandingsRaw(client: *Client, league: []const u8) !RawResponse {
    const allocator = client.allocator;
    var uri_buf: std.Io.Writer.Allocating = .init(allocator);
    defer uri_buf.deinit();
    try uri_buf.writer.print("{s}/api/v1/{s}/standings", .{ client.base_url, league });
    const payload: ?[]const u8 = null;

    var operation_headers = std.ArrayList(std.http.Header).empty;
    defer operation_headers.deinit(allocator);
    var operation_header_values = std.ArrayList([]u8).empty;
    defer {
        for (operation_header_values.items) |item| allocator.free(item);
        operation_header_values.deinit(allocator);
    }
    var auth_header: ?[]u8 = null;
    defer if (auth_header) |value| allocator.free(value);
    if (client.api_key.len > 0) {
        auth_header = try std.fmt.allocPrint(allocator, "Bearer {s}", .{client.api_key});
        try operation_headers.append(allocator, .{ .name = "Authorization", .value = auth_header.? });
    }

    return requestRawWithExtraHeaders(client, std.http.Method.GET, uri_buf.written(), payload, operation_headers.items);
}

pub fn getStandingsResult(client: *Client, league: []const u8) !ApiResult(LeagueStandings) {
    return parseRawResponse(LeagueStandings, try getStandingsRaw(client, league));
}

/////////////////
// Summary:
// List supported leagues
//
pub fn listLeagues(client: *Client) !Owned(LeagueList) {
    var result = try listLeaguesResult(client);
    switch (result) {
        .ok => |ok| return ok,
        .api_error => |*err| {
            err.deinit();
            return error.ResponseError;
        },
        .parse_error => |*err| {
            err.raw.deinit();
            return error.ResponseParseError;
        },
    }
}

pub fn listLeaguesRaw(client: *Client) !RawResponse {
    const allocator = client.allocator;
    var uri_buf: std.Io.Writer.Allocating = .init(allocator);
    defer uri_buf.deinit();
    try uri_buf.writer.print("{s}/api/v1/leagues", .{client.base_url});
    const payload: ?[]const u8 = null;

    var operation_headers = std.ArrayList(std.http.Header).empty;
    defer operation_headers.deinit(allocator);
    var operation_header_values = std.ArrayList([]u8).empty;
    defer {
        for (operation_header_values.items) |item| allocator.free(item);
        operation_header_values.deinit(allocator);
    }
    var auth_header: ?[]u8 = null;
    defer if (auth_header) |value| allocator.free(value);
    if (client.api_key.len > 0) {
        auth_header = try std.fmt.allocPrint(allocator, "Bearer {s}", .{client.api_key});
        try operation_headers.append(allocator, .{ .name = "Authorization", .value = auth_header.? });
    }

    return requestRawWithExtraHeaders(client, std.http.Method.GET, uri_buf.written(), payload, operation_headers.items);
}

pub fn listLeaguesResult(client: *Client) !ApiResult(LeagueList) {
    return parseRawResponse(LeagueList, try listLeaguesRaw(client));
}

/////////////////
// Summary:
// One team: last result, live game, and upcoming schedule
//
pub fn getTeam(client: *Client, league: []const u8, abbr: []const u8) !Owned(ScheduleTeamView) {
    var result = try getTeamResult(client, league, abbr);
    switch (result) {
        .ok => |ok| return ok,
        .api_error => |*err| {
            err.deinit();
            return error.ResponseError;
        },
        .parse_error => |*err| {
            err.raw.deinit();
            return error.ResponseParseError;
        },
    }
}

pub fn getTeamRaw(client: *Client, league: []const u8, abbr: []const u8) !RawResponse {
    const allocator = client.allocator;
    var uri_buf: std.Io.Writer.Allocating = .init(allocator);
    defer uri_buf.deinit();
    try uri_buf.writer.print("{s}/api/v1/{s}/{s}", .{ client.base_url, league, abbr });
    const payload: ?[]const u8 = null;

    var operation_headers = std.ArrayList(std.http.Header).empty;
    defer operation_headers.deinit(allocator);
    var operation_header_values = std.ArrayList([]u8).empty;
    defer {
        for (operation_header_values.items) |item| allocator.free(item);
        operation_header_values.deinit(allocator);
    }
    var auth_header: ?[]u8 = null;
    defer if (auth_header) |value| allocator.free(value);
    if (client.api_key.len > 0) {
        auth_header = try std.fmt.allocPrint(allocator, "Bearer {s}", .{client.api_key});
        try operation_headers.append(allocator, .{ .name = "Authorization", .value = auth_header.? });
    }

    return requestRawWithExtraHeaders(client, std.http.Method.GET, uri_buf.written(), payload, operation_headers.items);
}

pub fn getTeamResult(client: *Client, league: []const u8, abbr: []const u8) !ApiResult(ScheduleTeamView) {
    return parseRawResponse(ScheduleTeamView, try getTeamRaw(client, league, abbr));
}

/////////////////
// Summary:
// Scores for all leagues and date
//
// Description:
// Multi-league digest for one date: one Scoreboard per league in league order. Outages degrade additively, never by shape change: a failed league renders as a zero-game board with its slug in the top-level degraded list (zero games plus absent-from-degraded means off-day; present means outage, retry later; see digest.DigestJson). Game starts_at is UTC ISO-8601; text/HTML headings name the request zone (default ET). The source field names the upstream host (normally site.api.espn.com). Date-driven only (?date=YYYY-MM-DD, defaults to today); week is NOT fanned out.
//
pub fn getAll(client: *Client, date: ?[]const u8) !Owned(DigestJson) {
    var result = try getAllResult(client, date);
    switch (result) {
        .ok => |ok| return ok,
        .api_error => |*err| {
            err.deinit();
            return error.ResponseError;
        },
        .parse_error => |*err| {
            err.raw.deinit();
            return error.ResponseParseError;
        },
    }
}

pub fn getAllRaw(client: *Client, date: ?[]const u8) !RawResponse {
    const allocator = client.allocator;
    var uri_buf: std.Io.Writer.Allocating = .init(allocator);
    defer uri_buf.deinit();
    try uri_buf.writer.print("{s}/api/v1/all", .{client.base_url});
    var first_query = true;
    if (date) |value| {
        try appendQueryParam(&uri_buf.writer, &first_query, "date", value);
    }
    const payload: ?[]const u8 = null;

    var operation_headers = std.ArrayList(std.http.Header).empty;
    defer operation_headers.deinit(allocator);
    var operation_header_values = std.ArrayList([]u8).empty;
    defer {
        for (operation_header_values.items) |item| allocator.free(item);
        operation_header_values.deinit(allocator);
    }
    var auth_header: ?[]u8 = null;
    defer if (auth_header) |value| allocator.free(value);
    if (client.api_key.len > 0) {
        auth_header = try std.fmt.allocPrint(allocator, "Bearer {s}", .{client.api_key});
        try operation_headers.append(allocator, .{ .name = "Authorization", .value = auth_header.? });
    }

    return requestRawWithExtraHeaders(client, std.http.Method.GET, uri_buf.written(), payload, operation_headers.items);
}

pub fn getAllResult(client: *Client, date: ?[]const u8) !ApiResult(DigestJson) {
    return parseRawResponse(DigestJson, try getAllRaw(client, date));
}

/////////////////
// Summary:
// Scores for one league and date
//
// Description:
// Pass ?stream=sse (or Accept: text/event-stream) for a text-only SSE feed: framed as data: lines plus blank-line terminators, each event prefixed with the clear-screen escape \x1b[2J\x1b[H for in-place redraw, with : ping keepalive comments. Example: curl -N /nba?stream=sse. Text-only; JSON and HTML always return a single response. Pass ?week=N (strict positive integer; ESPN honors it only for football leagues, otherwise ignored). JSON Scoreboard: game starts_at is UTC ISO-8601 while text/HTML headings name the request zone (default ET); source names the upstream host (normally site.api.espn.com).
//
pub fn getScoreboard(client: *Client, league: []const u8, date: ?[]const u8, stream: ?[]const u8, week: ?i64) !Owned(Scoreboard) {
    var result = try getScoreboardResult(client, league, date, stream, week);
    switch (result) {
        .ok => |ok| return ok,
        .api_error => |*err| {
            err.deinit();
            return error.ResponseError;
        },
        .parse_error => |*err| {
            err.raw.deinit();
            return error.ResponseParseError;
        },
    }
}

pub fn getScoreboardRaw(client: *Client, league: []const u8, date: ?[]const u8, stream: ?[]const u8, week: ?i64) !RawResponse {
    const allocator = client.allocator;
    var uri_buf: std.Io.Writer.Allocating = .init(allocator);
    defer uri_buf.deinit();
    try uri_buf.writer.print("{s}/api/v1/{s}", .{ client.base_url, league });
    var first_query = true;
    if (date) |value| {
        try appendQueryParam(&uri_buf.writer, &first_query, "date", value);
    }
    if (stream) |value| {
        try appendQueryParam(&uri_buf.writer, &first_query, "stream", value);
    }
    if (week) |value| {
        try appendQueryParam(&uri_buf.writer, &first_query, "week", value);
    }
    const payload: ?[]const u8 = null;

    var operation_headers = std.ArrayList(std.http.Header).empty;
    defer operation_headers.deinit(allocator);
    var operation_header_values = std.ArrayList([]u8).empty;
    defer {
        for (operation_header_values.items) |item| allocator.free(item);
        operation_header_values.deinit(allocator);
    }
    var auth_header: ?[]u8 = null;
    defer if (auth_header) |value| allocator.free(value);
    if (client.api_key.len > 0) {
        auth_header = try std.fmt.allocPrint(allocator, "Bearer {s}", .{client.api_key});
        try operation_headers.append(allocator, .{ .name = "Authorization", .value = auth_header.? });
    }

    return requestRawWithExtraHeaders(client, std.http.Method.GET, uri_buf.written(), payload, operation_headers.items);
}

pub fn getScoreboardResult(client: *Client, league: []const u8, date: ?[]const u8, stream: ?[]const u8, week: ?i64) !ApiResult(Scoreboard) {
    return parseRawResponse(Scoreboard, try getScoreboardRaw(client, league, date, stream, week));
}

/////////////////
// Summary:
// One game with linescore and scoring plays
//
// Description:
// The second segment is a game only when it is all digits; anything else routes to the team view.
//
pub fn getGame(client: *Client, league: []const u8, id: []const u8) !Owned(DetailGame) {
    var result = try getGameResult(client, league, id);
    switch (result) {
        .ok => |ok| return ok,
        .api_error => |*err| {
            err.deinit();
            return error.ResponseError;
        },
        .parse_error => |*err| {
            err.raw.deinit();
            return error.ResponseParseError;
        },
    }
}

pub fn getGameRaw(client: *Client, league: []const u8, id: []const u8) !RawResponse {
    const allocator = client.allocator;
    var uri_buf: std.Io.Writer.Allocating = .init(allocator);
    defer uri_buf.deinit();
    try uri_buf.writer.print("{s}/api/v1/{s}/{s}", .{ client.base_url, league, id });
    const payload: ?[]const u8 = null;

    var operation_headers = std.ArrayList(std.http.Header).empty;
    defer operation_headers.deinit(allocator);
    var operation_header_values = std.ArrayList([]u8).empty;
    defer {
        for (operation_header_values.items) |item| allocator.free(item);
        operation_header_values.deinit(allocator);
    }
    var auth_header: ?[]u8 = null;
    defer if (auth_header) |value| allocator.free(value);
    if (client.api_key.len > 0) {
        auth_header = try std.fmt.allocPrint(allocator, "Bearer {s}", .{client.api_key});
        try operation_headers.append(allocator, .{ .name = "Authorization", .value = auth_header.? });
    }

    return requestRawWithExtraHeaders(client, std.http.Method.GET, uri_buf.written(), payload, operation_headers.items);
}

pub fn getGameResult(client: *Client, league: []const u8, id: []const u8) !ApiResult(DetailGame) {
    return parseRawResponse(DetailGame, try getGameRaw(client, league, id));
}

pub const resources = struct {
    pub const api = struct {
        pub fn getgame_(client: *Client, league: []const u8, id: []const u8) !Owned(DetailGame) {
            return getGame(client, league, id);
        }
        pub fn getgame_Result(client: *Client, league: []const u8, id: []const u8) !ApiResult(DetailGame) {
            return getGameResult(client, league, id);
        }
        pub fn getscoreboard_(client: *Client, league: []const u8, date: ?[]const u8, stream: ?[]const u8, week: ?i64) !Owned(Scoreboard) {
            return getScoreboard(client, league, date, stream, week);
        }
        pub fn getscoreboard_Result(client: *Client, league: []const u8, date: ?[]const u8, stream: ?[]const u8, week: ?i64) !ApiResult(Scoreboard) {
            return getScoreboardResult(client, league, date, stream, week);
        }
        pub fn getteam_(client: *Client, league: []const u8, abbr: []const u8) !Owned(ScheduleTeamView) {
            return getTeam(client, league, abbr);
        }
        pub fn getteam_Result(client: *Client, league: []const u8, abbr: []const u8) !ApiResult(ScheduleTeamView) {
            return getTeamResult(client, league, abbr);
        }
        pub const all = struct {
            pub fn get(client: *Client, date: ?[]const u8) !Owned(DigestJson) {
                return getAll(client, date);
            }
            pub fn getResult(client: *Client, date: ?[]const u8) !ApiResult(DigestJson) {
                return getAllResult(client, date);
            }
        };
        pub const leagues = struct {
            pub fn list(client: *Client) !Owned(LeagueList) {
                return listLeagues(client);
            }
            pub fn listResult(client: *Client) !ApiResult(LeagueList) {
                return listLeaguesResult(client);
            }
        };
        pub const standings = struct {
            pub fn get(client: *Client, league: []const u8) !Owned(LeagueStandings) {
                return getStandings(client, league);
            }
            pub fn getResult(client: *Client, league: []const u8) !ApiResult(LeagueStandings) {
                return getStandingsResult(client, league);
            }
        };
    };
};

pub const api = resources.api;
